name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
          log-level: warn
          command: check
    - name: Check fmt
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy
    - name: Run tests
      run: cargo test
